insert into public.projects (
  name,
  full_title,
  slug,
  short_description,
  summary,
  edital,
  registration_number,
  approved_amount,
  executed_amount,
  status,
  current_stage,
  modality,
  class_name,
  proponent,
  proponent_document,
  city,
  state,
  start_date,
  end_date,
  notes
) values (
  'Reféns',
  'Formação de Artistas de Rua e Montagem do Espetáculo Reféns',
  'formacao-artistas-rua-espetaculo-refens',
  'Projeto de formação cênica e montagem teatral com artistas de rua.',
  'Formação organizada em aulas, ensaios, registros documentais, mídia e prestação de contas final.',
  'Circuito Catarinense de Cultura PNAB SC 2026',
  '000937',
  50000,
  8500,
  'Classificado',
  'Habilitação em andamento',
  'Ações de Qualificação e Formação',
  'Classe II',
  'Cia de Artes Viva',
  '00.000.000/0001-00',
  'Florianópolis',
  'SC',
  '2026-08-01',
  '2027-07-31',
  'Seed inicial do sistema.'
) on conflict (slug) do nothing;
