import { z } from "zod";

import {
  certificateFooterLayouts,
  certificateLogoPositions,
  certificatePageOrientations,
  certificateStatuses,
} from "./types";

const checkbox = z.boolean();

export const certificateGenerationSchema = z.object({
  projectId: z.string().min(1, "Projeto obrigatório"),
  templateId: z.string().min(1, "Modelo obrigatório"),
  studentIds: z.array(z.string()).default([]),
  courseName: z.string().min(1, "Nome do curso obrigatório"),
  modality: z.string().min(1, "Modalidade obrigatória"),
  area: z.string().min(1, "Área cultural obrigatória"),
  workload: z.string().min(1, "Carga horária obrigatória"),
  city: z.string().min(1, "Cidade obrigatória"),
  issueDate: z.string().min(1, "Data de emissão obrigatória"),
  frontText: z.string().min(1, "Texto da frente obrigatório"),
  conclusionText: z.string().min(1, "Texto de conclusão obrigatório"),
  programContent: z.string().min(1, "Conteúdo programático obrigatório"),
  teacher: z.string().min(1, "Professor obrigatório"),
  directorGeneral: z.string().min(1, "Diretor geral obrigatório"),
  executiveDirector: z.string().min(1, "Diretor executivo obrigatório"),
  registry: z.string().min(1, "Registro obrigatório"),
  book: z.string().optional().default(""),
  folio: z.string().optional().default(""),
  notes: z.string().optional().default(""),
  status: z.enum(certificateStatuses),
  showStudentCpf: checkbox.default(true),
  allowMissingCpf: checkbox.default(true),
  includeBackSide: checkbox.default(true),
  backColumns: z.union([z.literal(1), z.literal(2)]).default(2),
});

export type CertificateGenerationValues = z.infer<typeof certificateGenerationSchema>;

export const certificateSettingsSchema = z.object({
  logoMainUrl: z.string().optional().nullable().default(null),
  logoSecondaryUrl: z.string().optional().nullable().default(null),
  logoInstitutionUrl: z.string().optional().nullable().default(null),
  logoCiaUrl: z.string().optional().nullable().default(null),
  sponsorLogosEnabled: checkbox.default(true),
  primaryColor: z.string().min(1),
  secondaryColor: z.string().min(1),
  borderColor: z.string().min(1),
  titleColor: z.string().min(1),
  titleFont: z.string().min(1),
  bodyFont: z.string().min(1),
  modelName: z.string().min(1),
  pageOrientation: z.enum(certificatePageOrientations),
  marginTop: z.coerce.number().min(0),
  marginBottom: z.coerce.number().min(0),
  marginLeft: z.coerce.number().min(0),
  marginRight: z.coerce.number().min(0),
  borderEnabled: checkbox.default(true),
  borderThickness: z.coerce.number().min(0),
  backgroundEnabled: checkbox.default(false),
  backgroundImageUrl: z.string().optional().nullable().default(null),
  backgroundOpacity: z.coerce.number().min(0).max(1),
  frontText: z.string().min(1),
  conclusionText: z.string().min(1),
  showStudentCpf: checkbox.default(true),
  showCityDate: checkbox.default(true),
  showModality: checkbox.default(true),
  showProjectName: checkbox.default(true),
  showWorkloadFront: checkbox.default(true),
  showFooterLogos: checkbox.default(true),
  showFooterFront: checkbox.default(true),
  showFooterBack: checkbox.default(true),
  useSameFooterOnBack: checkbox.default(true),
  showCategoryTitles: checkbox.default(true),
  showDividers: checkbox.default(true),
  logoSpacing: z.coerce.number().min(0),
  footerMarginTopMm: z.coerce.number().min(0),
  footerMarginBottomMm: z.coerce.number().min(0),
  footerLayout: z.enum(certificateFooterLayouts),
  footerHeight: z.coerce.number().min(0),
  footerLogoSize: z.coerce.number().min(0),
  backTitle: z.string().min(1),
  programContent: z.string().min(1),
  backColumns: z.union([z.literal(1), z.literal(2)]),
  showBackWorkload: checkbox.default(true),
  showBackTeacher: checkbox.default(true),
  showBackRegistry: checkbox.default(true),
  showBackBookFolio: checkbox.default(true),
  showBackSignature: checkbox.default(true),
  showBackLogos: checkbox.default(true),
  finalBackImageEnabled: checkbox.default(false),
  finalBackImageUrl: z.string().optional().nullable().default(null),
  finalBackImagePosition: z.enum(certificateLogoPositions),
  finalBackImageWidth: z.coerce.number().min(0),
  finalBackImageHeight: z.coerce.number().min(0),
  finalBackImageMarginTop: z.coerce.number().min(0),
  finalBackImageMarginBottom: z.coerce.number().min(0),
  finalBackImageShowOnPdf: checkbox.default(true),
  finalBackImageKeepAspectRatio: checkbox.default(true),
  allow1Signature: checkbox.default(true),
  allow2Signatures: checkbox.default(true),
  allow3Signatures: checkbox.default(true),
  bookLabel: z.string().min(1),
  folioLabel: z.string().min(1),
});

export type CertificateSettingsValues = z.infer<typeof certificateSettingsSchema>;
