import { formatCertificateNumber } from "./certificate-number";
import type {
  CertificateBatch,
  CertificateRecord,
  CertificateSettings,
  CertificateSignature,
  CertificateSponsorLogo,
  CertificateTemplate,
} from "./types";

export const defaultCertificateSettings: CertificateSettings = {
  logoMainUrl: null,
  logoSecondaryUrl: null,
  logoInstitutionUrl: null,
  logoCiaUrl: null,
  sponsorLogosEnabled: true,
  primaryColor: "#14532d",
  secondaryColor: "#b7791f",
  borderColor: "#d6bb7e",
  titleColor: "#174a2d",
  titleFont: "Inter",
  bodyFont: "Arial",
  modelName: "Padrão institucional",
  pageOrientation: "paisagem",
  marginTop: 24,
  marginBottom: 24,
  marginLeft: 28,
  marginRight: 28,
  borderEnabled: true,
  borderThickness: 2,
  backgroundEnabled: false,
  backgroundImageUrl: null,
  backgroundOpacity: 0.1,
  frontText:
    "Certificamos que {{nome}} participou do projeto {{projeto}} e concluiu as atividades previstas.",
  conclusionText:
    "A participação foi registrada conforme o diário de classe e os documentos do projeto cultural.",
  showStudentCpf: true,
  showCityDate: true,
  showModality: true,
  showProjectName: true,
  showWorkloadFront: true,
  showFooterLogos: true,
  showFooterFront: true,
  showFooterBack: true,
  useSameFooterOnBack: true,
  showCategoryTitles: true,
  showDividers: true,
  logoSpacing: 14,
  footerMarginTopMm: 6,
  footerMarginBottomMm: 6,
  footerLayout: "categorias",
  footerHeight: 64,
  footerLogoSize: 32,
  backTitle: "CONTEÚDO PROGRAMÁTICO",
  programContent:
    "1. Acolhimento e integração\n2. Desenvolvimento artístico e técnico\n3. Práticas de criação\n4. Encerramento e devolutiva",
  backColumns: 2,
  showBackWorkload: true,
  showBackTeacher: true,
  showBackRegistry: true,
  showBackBookFolio: true,
  showBackSignature: true,
  showBackLogos: true,
  finalBackImageEnabled: false,
  finalBackImageUrl: null,
  finalBackImagePosition: "centro",
  finalBackImageWidth: 52,
  finalBackImageHeight: 86,
  finalBackImageMarginTop: 16,
  finalBackImageMarginBottom: 16,
  finalBackImageShowOnPdf: true,
  finalBackImageKeepAspectRatio: true,
  allow1Signature: true,
  allow2Signatures: true,
  allow3Signatures: true,
  bookLabel: "Livro",
  folioLabel: "Folhas",
};

export function buildDefaultCertificateTemplate(projectId: string | null): CertificateTemplate {
  return {
    id: projectId ? `${projectId}-certificate-template` : "certificate-template-default",
    projectId,
    name: "Modelo institucional",
    isDefault: true,
    primaryColor: defaultCertificateSettings.primaryColor,
    secondaryColor: defaultCertificateSettings.secondaryColor,
    titleColor: defaultCertificateSettings.titleColor,
    borderColor: defaultCertificateSettings.borderColor,
    borderEnabled: defaultCertificateSettings.borderEnabled,
    backgroundImageUrl: defaultCertificateSettings.backgroundImageUrl,
    logoMainUrl: defaultCertificateSettings.logoMainUrl,
    logoSecondaryUrl: defaultCertificateSettings.logoSecondaryUrl,
    footerLogosEnabled: defaultCertificateSettings.showFooterLogos,
    frontText: defaultCertificateSettings.frontText,
    conclusionText: defaultCertificateSettings.conclusionText,
    backTitle: defaultCertificateSettings.backTitle,
    programContent: defaultCertificateSettings.programContent,
    workload: "40h",
    city: "Florianópolis",
    showStudentCpf: defaultCertificateSettings.showStudentCpf,
    showWorkloadFront: defaultCertificateSettings.showWorkloadFront,
    showModality: defaultCertificateSettings.showModality,
    showProjectName: defaultCertificateSettings.showProjectName,
    backColumns: defaultCertificateSettings.backColumns,
    finalBackImageEnabled: defaultCertificateSettings.finalBackImageEnabled,
    finalBackImageUrl: defaultCertificateSettings.finalBackImageUrl,
    finalBackImagePosition: defaultCertificateSettings.finalBackImagePosition,
    finalBackImageWidth: defaultCertificateSettings.finalBackImageWidth,
    finalBackImageHeight: defaultCertificateSettings.finalBackImageHeight,
    finalBackImageMarginTop: defaultCertificateSettings.finalBackImageMarginTop,
    finalBackImageMarginBottom: defaultCertificateSettings.finalBackImageMarginBottom,
    finalBackImageShowOnPdf: defaultCertificateSettings.finalBackImageShowOnPdf,
    finalBackImageKeepAspectRatio: defaultCertificateSettings.finalBackImageKeepAspectRatio,
    showBackLogos: defaultCertificateSettings.showBackLogos,
    showBackWorkload: defaultCertificateSettings.showBackWorkload,
    showBackTeacher: defaultCertificateSettings.showBackTeacher,
    showBackRegistry: defaultCertificateSettings.showBackRegistry,
    showBackBookFolio: defaultCertificateSettings.showBackBookFolio,
    showBackSignature: defaultCertificateSettings.showBackSignature,
    pageOrientation: defaultCertificateSettings.pageOrientation,
    marginTop: defaultCertificateSettings.marginTop,
    marginBottom: defaultCertificateSettings.marginBottom,
    marginLeft: defaultCertificateSettings.marginLeft,
    marginRight: defaultCertificateSettings.marginRight,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

export function buildDefaultSignatures(templateId: string): CertificateSignature[] {
  return [
    {
      id: `${templateId}-sig-1`,
      templateId,
      name: "Marcel Eduardo Domingues do Prado",
      role: "Diretor geral",
      signatureUrl: null,
      order: 1,
      showOnFront: true,
      showOnBack: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: `${templateId}-sig-2`,
      templateId,
      name: "Kaique",
      role: "Diretor executivo",
      signatureUrl: null,
      order: 2,
      showOnFront: true,
      showOnBack: true,
      createdAt: new Date().toISOString(),
    },
  ];
}

export function buildDefaultSponsorLogos(templateId: string): CertificateSponsorLogo[] {
  return [
    {
      id: `${templateId}-sponsor-1`,
      templateId,
      name: "Cia de Artes Viva",
      type: "instituição",
      logoUrl: null,
      fileName: null,
      fileType: null,
      fileSize: null,
      imageWidth: null,
      imageHeight: null,
      displayWidthMm: 36,
      maxHeightMm: 16,
      position: "centro",
      order: 1,
      displayOrder: 1,
      size: 32,
      showOnFront: true,
      showOnBack: true,
      isActive: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: `${templateId}-sponsor-2`,
      templateId,
      name: "PNAB",
      type: "patrocínio",
      logoUrl: null,
      fileName: null,
      fileType: null,
      fileSize: null,
      imageWidth: null,
      imageHeight: null,
      displayWidthMm: 32,
      maxHeightMm: 16,
      position: "centro",
      order: 2,
      displayOrder: 2,
      size: 28,
      showOnFront: true,
      showOnBack: true,
      isActive: true,
      createdAt: new Date().toISOString(),
    },
    {
      id: `${templateId}-sponsor-3`,
      templateId,
      name: "Apoio Cultural",
      type: "apoio",
      logoUrl: null,
      fileName: null,
      fileType: null,
      fileSize: null,
      imageWidth: null,
      imageHeight: null,
      displayWidthMm: 28,
      maxHeightMm: 14,
      position: "centro",
      order: 3,
      displayOrder: 3,
      size: 24,
      showOnFront: true,
      showOnBack: true,
      isActive: true,
      createdAt: new Date().toISOString(),
    },
  ];
}

export function buildDefaultCertificates(projectId: string): CertificateRecord[] {
  const year = new Date().getFullYear();

  return [
    {
      id: `${projectId}-cert-1`,
      projectId,
      templateId: `${projectId}-certificate-template`,
      participantId: `${projectId}-part-1`,
      certificateNumber: formatCertificateNumber("CERT", year, 1),
      studentName: "Participante 01",
      studentDocument: "000.000.000-00",
      courseName: "Formação cultural",
      modality: "Oficina",
      workload: "40h",
      city: "Florianópolis",
      issueDate: "2026-06-19",
      status: "Emitido",
      pdfUrl: null,
      generatedBy: "Sistema",
      generatedAt: new Date().toISOString(),
      canceledAt: null,
      cancelReason: null,
      createdAt: new Date().toISOString(),
    },
    {
      id: `${projectId}-cert-2`,
      projectId,
      templateId: `${projectId}-certificate-template`,
      participantId: `${projectId}-part-2`,
      certificateNumber: formatCertificateNumber("CERT", year, 2),
      studentName: "Participante 02",
      studentDocument: "000.000.000-00",
      courseName: "Formação cultural",
      modality: "Oficina",
      workload: "40h",
      city: "Florianópolis",
      issueDate: "2026-06-19",
      status: "Pronto",
      pdfUrl: null,
      generatedBy: null,
      generatedAt: null,
      canceledAt: null,
      cancelReason: null,
      createdAt: new Date().toISOString(),
    },
    {
      id: `${projectId}-cert-3`,
      projectId,
      templateId: `${projectId}-certificate-template`,
      participantId: `${projectId}-part-3`,
      certificateNumber: formatCertificateNumber("CERT", year, 3),
      studentName: "Participante 03",
      studentDocument: "",
      courseName: "Formação cultural",
      modality: "Oficina",
      workload: "40h",
      city: "Florianópolis",
      issueDate: "2026-06-19",
      status: "Rascunho",
      pdfUrl: null,
      generatedBy: null,
      generatedAt: null,
      canceledAt: null,
      cancelReason: null,
      createdAt: new Date().toISOString(),
    },
  ];
}

export function buildDefaultBatches(projectId: string): CertificateBatch[] {
  return [
    {
      id: `${projectId}-batch-1`,
      projectId,
      templateId: `${projectId}-certificate-template`,
      name: "Lote inicial da turma",
      totalCertificates: 2,
      pdfUrl: null,
      zipUrl: null,
      generatedBy: "Sistema",
      generatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  ];
}
