import type { Participant } from "./types";

export const participants: Participant[] = [
  {
    id: "part-1",
    projectId: "refens",
    fullName: "Participante 01",
    document: "000.000.000-00",
    birthDate: "2001-04-12",
    phone: "(48) 98888-1001",
    email: "participante01@email.com",
    neighborhood: "Centro",
    address: "Rua das Artes, 100",
    guardianName: null,
    guardianPhone: null,
    imageAuthorization: true,
    participationAuthorization: true,
    pedagogicalNotes: "Boa presença corporal e disponibilidade para criação.",
    status: "Ativo",
    attendanceRate: 100,
  },
  {
    id: "part-2",
    projectId: "refens",
    fullName: "Participante 02",
    document: "000.000.000-00",
    birthDate: "2007-09-20",
    phone: "(48) 98888-1002",
    email: "participante02@email.com",
    neighborhood: "Serraria",
    address: "Rua da Cultura, 230",
    guardianName: "Responsável legal",
    guardianPhone: "(48) 98888-2002",
    imageAuthorization: true,
    participationAuthorization: true,
    pedagogicalNotes: "Menor de idade; manter autorização do responsável anexada.",
    status: "Ativo",
    attendanceRate: 90,
  },
  {
    id: "part-3",
    projectId: "refens",
    fullName: "Participante 03",
    document: "",
    birthDate: "1998-02-03",
    phone: "(48) 98888-1003",
    email: "",
    neighborhood: "Campinas",
    address: "Avenida Viva, 45",
    guardianName: null,
    guardianPhone: null,
    imageAuthorization: false,
    participationAuthorization: true,
    pedagogicalNotes: "Pendente autorização de imagem.",
    status: "Selecionado",
    attendanceRate: 0,
  },
];

export async function listParticipants() {
  return participants;
}
